### ISSUE TITLE
There's no "options" page

### ISSUE THREAD

**Issue by tunnckoCore** [rhardih/ekill#6]
Nor `ctrl+k` works. So.. there is no way to use it.

Other than that... great idea!

**Comment by rhardih** [comment]
Since there's really settings for the plugin, there's no _options page_.

Assigning hotkeys to plugins, is part of the general settings for extensions in Chrome. Try to go chrome://extensions and click the "burger" in the upper left hand corner.

<img width="265" alt="screen shot 2018-10-04 at 08 43 38" src="https://user-images.githubusercontent.com/124250/46457178-b6835800-c7b1-11e8-95df-977920e7c0f6.png">

You should see this foldout menu, with an item named "Keyboard shortcuts"; there you'll be able to assign Ctrl+k or any other hotkey you'd like.

**Comment by tunnckoCore** [comment]
Oooh, yea, i don't know why i thought that "chrome extensions" is "extension's options" :D
